apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.db.name }}
  labels:
    env: {{ .Values.namespace }}
    name: postgres-{{ .Values.namespace }}
    {{- include "common_labels" . | indent 4 }}
spec:
  serviceName: {{ .Values.db.servicename | quote }}
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      name: postgres-{{ .Values.namespace }}
      env: {{ .Values.namespace }}
  template:
    metadata:
      labels:
        name: postgres-{{ .Values.namespace }}
        env: {{ .Values.namespace }}
        {{- include "common_labels" . | indent 8 }}
    spec:
      {{- if .Values.db.security }}
      {{- toYaml .Values.db.security | nindent 6 }}
      {{- end }}
      initContainers:
        - name: fix-permissions
          image: busybox
          securityContext:
            runAsUser: 0
          command: ["sh", "-c", "chown -R 999:999 /var/lib/postgresql/18/docker"]
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/18/docker
      containers:
        - name: {{ .Values.db.name }}
          image: postgres
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/18/docker
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.db.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.db.storage }}
