{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.redis.name }}
  labels:
    env: {{ .Values.namespace }}
    name: redis-pod-{{ .Values.namespace }}
{{- include "common_labels" . | indent 4 }}
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
     - containerPort: 6379
{{- end }}