apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-regcred
  namespace: stage
spec:
  encryptedData:
    .dockerconfigjson: AgCXLefdrZoG8tYU6biIUVArdMtkeQ+2xIRRVKw+5MeaFirvuZbGUFmC7vyNwMz9OKTD4FYkXccr5PNHrFfYjNhG0EBr6jzG6r/UqkcJhJNAHvbJnhsRHXJgttxAfpS1+IaaCy2HofH3aYngVWD09m2zrg8BlrYL8W2DY5cps/xgyPFW6Xxo32+K1R0dFcUZvZmja2AB7zUrhkGIKkqsO3/M/zn5PHScTC1rTK/lJM0mkDTEeaO/WHVxIjwM+6rf9K5a2r+59nBRFJGIWTyEx4WhRomARcl52aFBVi8p97dC/Y8zvlT5cO/KyGx/zbjPFpnLqy2iw13D4+nxZSuBO44eU36TuDolDH+3g43plTSRhl0/LKNO+ytrJJm1RN+Re7JFQTaYCG4cWRaEvXvM+F56Xe9v4C4U183o43RltMQ2aQorUYHrgeOn8KbVXDkbPOegBh3McicdJDwzG8pybZv+IjgwQrhftdzIqeq1AaHZVT6FUd4DKIIUDjXRGpj+x9dqefpnSQ5xeBszO0VWUz0EpY7tAo26bEVCPxxXMX5RSnpIEdSXWCu73rm7vs9kKzAOHQ4NE3uYqBsNcijucDHn4oFt7YOzovOsSD8GvIvzn1lTlm575MV8dK3dtDFI9WQoyMDK2UhFIhHz3VUDkXaXfATv7yeZVSl9EC3PuXP0CB2R3ZJ18Y/kYmv304ouRtFVzyjaXJ1MMxyE4vSrcoUDSp8VGtc7iufbNA/O3OHDv/nIkuILTN7cOdNPdjwc/i5qGAMYMp4Lk75Ndh4HMHO7H8sbd9TUFMh/XmtU+H8PqMX5UJcy6BFm9xH6E2Sqax53ZLBhTutdDpTQtUxF6goDtKEBEqmq/E+2GopeQput34Kkg4BPNlNRNWoxm8WwEXX4ALNnSJEDXxiVMGK0mCQBynJXz0PwnsdjwXIqNOQ2OtnI2OGpxbyA6TgbpfiF+zkPwoMf41gTfA==
  template:
    metadata:
      name: gitlab-regcred
      namespace: stage
    type: kubernetes.io/dockerconfigjson
