secret:
 create: false
 name: csi-s3-secret
 namespace: kube-system

storageClass:
 create: true
 name: yc-s3-opensearch
 provisioner: ru.yandex.s3.csi
 reclaimPolicy: Delete
 volumeBindingMode: Immediate
 allowVolumeExpansion: false

 parameters:
  options: "--dir-mode=0777 --file-mode=0666"
  createBucketIfNotExists: "false"

 csi:
  provisionerSecretName: csi-s3-secret
  provisionerSecretNamespace: kube-system
  nodeStageSecretName: csi-s3-secret
  nodeStageSecretNamespace: kube-system
  nodePublishSecretName: csi-s3-secret
  nodePublishSecretNamespace: kube-system

controller:
 replicas: 1

node:
 tolerations:
 - operator: Exists