apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-hpa
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.16.1
      helm: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: kedahpa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true