apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app-deploy-autoscale
  namespace: prod
spec:
  scaleTargetRef: # Указываем что именно хотим скалировать
    name: vote-app-deployment
    kind: Deployment

  minReplicaCount: 1 # Мин.Кол-во реплик    
  maxReplicaCount: 20 # Макс.Кол-во реплик

  cooldownPeriod: 300       # 300 сек перед уменьшением кол-ва реплик
  pollingInterval: 15       # Как часто кеда опрашивает наши метрики(по дефолту 15сек как и HPA, можем поменять при необходимости)

  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0 # Окно стабилизации здесь 0 сек, т.е кол-во подов будет расти без подтверждения времени
          policies:
          - type: Pods
            value: 4            # +4 пода за шаг каждые 15сек если нагрузка растёт
            periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300   # подтверждение падения 300 сек, кол-во подов будет уменьшаться только если в течении 300секунд метрики будут ниже указанного нами уровня
          policies:
          - type: Pods
            value: 2            # -2 пода за шаг каждые 15сек если нагрузка падает(но у нас есть окностабилизации, которое не даст рушить скаллинг поды каждые 15 сек, он будет ждать 300секунд, рушить поды, потом через 15сек опять захочет сломать, но будет ждать ещё 300сек)
            periodSeconds: 15
# P.S Методика скалирования выбрана не случайна, у нас выбран метод жесткого скалирования вверх и медленного скаллирования вниз для того, чтобы наше приложение было более пользовательско-приветственное и они имели к нему быстрый доступ
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"   # если >75% — скейлимся
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc:9090 # здесь указываем куда пойдем за метриками
        query: |
          sum(rate(http_requests_total{app="app-deploy"}[1m])) # указываем саму метрики
        threshold: "100"  # например: если > 100 http запросов в минуту, то скелимся